/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetOwnerResult { 
    firstName?: string | null;
    lastName?: string | null;
    city?: string | null;
    address?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    mobileNumber?: string | null;
    postalCode?: string | null;
    country?: string | null;
    personalNumber?: string | null;
    passportNumber?: string | null;
    idCardNumber?: string | null;
    uid?: string | null;
}

