/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SelectedDiagnosis } from './selectedDiagnosis';
import { SelectedPrescription } from './selectedPrescription';
import { SelectedService } from './selectedService';

export interface CreateHealthRecordCommand { 
    animalUid?: string;
    control?: Date;
    temperature?: string;
    weight?: string;
    anamnesis?: string;
    clinicalExamination?: string;
    recommendation?: string;
    otherFindings?: string;
    note?: string;
    therapy?: string;
    diagnoses?: Array<SelectedDiagnosis>;
    services?: Array<SelectedService>;
    prescriptions?: Array<SelectedPrescription>;
}