/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Breed } from './breed';
import { Gender } from './gender';
import { Owner } from './owner';
import { Species } from './species';

export interface GetAnimalsResult { 
    animalUid?: string;
    personalNumber?: string;
    name?: string;
    species?: Species;
    breed?: Breed;
    gender?: Gender;
    birthDateTime?: Date;
    passportNumber?: string;
    owner?: Owner;
    warning?: string;
    lastModifiedDateTimeUtc?: Date;
}