/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Gender } from './gender';
import { Owner } from './owner';

export interface GetAnimalResult { 
    animalUid?: string;
    personalNumber?: string;
    name?: string;
    species?: string;
    breed?: string;
    gender?: Gender;
    color?: string;
    birthDateTime?: Date;
    passportNumber?: string;
    viIssuesAPassport?: string;
    owner?: Owner;
    warning?: string;
    identification?: string;
    markingDateTimeUtc?: Date;
    pedigree?: string;
    sterilized?: boolean;
    sterilizedDateTimeUtc?: Date;
    lastModifiedDateTimeUtc?: Date;
}