/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GetOwnerResult { 
    uid?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    phoneNumber?: string;
    mobileNumber?: string;
    city?: string;
    address?: string;
    postalCode?: string;
    country?: string;
    personalNumber?: string;
    passportNumber?: string;
    idCardNumber?: string;
    warning?: string;
    unpaidExpenses?: number;
}