/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Animal } from './animal';
import { Owner } from './owner';

export interface HealthRecord { 
    healthRecordUid?: string;
    animal?: Animal;
    owner?: Owner;
}