export * from './animals.service';
import { AnimalsService } from './animals.service';
export * from './healthRecords.service';
import { HealthRecordsService } from './healthRecords.service';
export * from './owners.service';
import { OwnersService } from './owners.service';
export * from './prescriptions.service';
import { PrescriptionsService } from './prescriptions.service';
export * from './veterinarians.service';
import { VeterinariansService } from './veterinarians.service';
export * from './veterinaryClinicsControllers.service';
import { VeterinaryClinicsControllersService } from './veterinaryClinicsControllers.service';
export const APIS = [AnimalsService, HealthRecordsService, OwnersService, PrescriptionsService, VeterinariansService, VeterinaryClinicsControllersService];
